baseurl = "https://amazing-hugo-site.netlify.com/"
title = "Hugo website"
copyright = "Copyright &copy; 2018 - Sudip Nayak"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Sudip Nayak"
    github = "https://github.com/Sudip7"
    gitlab = ""
    linkedin = ""
    facebook = ""
    twitter = "https://twitter.com/iSudip7"
    instagram = ""

[params]
    tagline = "A Hugo website for creative and technical writing"

[[menu.main]]
    name = "Home" #Name in the navigation bar
    weight = 10 #The larger the weight, the more on the right this item will be
    url = "/" #URL address
[[menu.main]]
    name = "Posts"
    weight = 20
    url = "/posts/"
